name: Test GHA workflow

env:
  TIER: ${{
    ( github.ref == 'refs/heads/dev' && 'dev')
    || ( github.ref == 'refs/heads/qa' && 'qa')
    || ( github.ref == 'refs/heads/prod' && 'prod')
    || 'unspecified'
    }}

on:
  push:
    branches:
      - dev
      - qa

jobs:
  environment: qa
  env:
    SECRET: ${{ secrets.SECRET }}

  preconditions:
    # environment: ${{TIER}}
    # environment: dev
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check for required secrets and environment variables
        run: |
          #!/bin/bash
          echo $SECRET > secret.txt
          tail secret.txt
          node index.js
